# Generated by Django 5.2.3 on 2025-07-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(default='1234567890', max_length=13)),
                ('published_date', models.DateField(default='2000-01-01')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
