# Generated by Django 5.2.3 on 2025-08-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='new_field',
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='1234567890', max_length=13),
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
