name: Run unit tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/install-dependencies

      - name: Run PyTest
        run: pytest

  runmigrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/install-dependencies

      - name: Run django migrate
        run: python manage.py migrate

  migrations-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/install-dependencies

      - name: Run django migrate
        # this checks exit status: of it is 0 - migrations successful
        run: python manage.py makemigrations --check

  build-docker-image:
    runs-on: ubuntu-latest
    needs:
      - test
      - runmigrations
      - migrations-check
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/vadym11/devopsproject2025
          # find how to set env and secrets from video
#          images: ${{ env.REGISTRY }}/{{ env.IMAGE_NAME }} skipped for now

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }} # main
          push: true
          labels: ${{ steps.meta.outputs.labels }}

#  docker build -t ghcr.io/vadym11/devopsproject2025