name: Run unit tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-lates

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install -upgrade pip
          pip install -r requirements.txt

      - name: Run PyTest
        run: pytest